version: '3.8'

services:
  # --- Database Services ---
  postgres:
    image: postgres:16-alpine
    container_name: digital_logistics_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      POSTGRES_DB: ${POSTGRES_DB:-logistics}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - logistics-net

  pgadmin:
    image: dpage/pgadmin4:8.4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      - postgres
    networks:
      - logistics-net
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  # --- SonarQube Services ---
  sonarqube_db:
    image: postgres:16-alpine
    container_name: sonarqube_postgres_db
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
    volumes:
      - sonar_pg_data:/var/lib/postgresql/data
    networks:
      - logistics-net

  sonarqube:
    image: sonarqube:10.4-community
    container_name: sonarqube_ci
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube_db:5432/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    ports:
      - "9000:9000"
    depends_on:
      - sonarqube_db
    networks:
      - logistics-net
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

  # --- ELK Stack (Security DISABLED) ---
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false  # <--- هذا هو الحل السحري
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - logistics-net

  logstash:
    image: docker.elastic.co/logstash/logstash:8.11.1
    container_name: logstash
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
    volumes:
      - ./logstash-pipeline:/usr/share/logstash/pipeline
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      XPACK_MONITORING_ENABLED: "false"
    depends_on:
      - elasticsearch
    networks:
      - logistics-net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      # لا نحتاج لـ User/Password لأن Security معطل
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - logistics-net

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8083:8080"


  # --- Spring Boot App ---
  app:
    build: .
    container_name: digital_logistics_app
    depends_on:
      - postgres
      - logstash
    environment:
      SERVER_PORT: ${SERVER_PORT:-8080}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      LOGSTASH_HOST: logstash
      LOGSTASH_PORT: 5000
    ports:
      - "${SERVER_PORT:-8080}:${SERVER_PORT:-8080}"
    networks:
      - logistics-net

volumes:
  pg_data:
  es_data:
  pgadmin_data:
  sonar_pg_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:

networks:
  logistics-net:
    driver: bridge